package pt.gois.dtServices.entity;
// Generated 1/jun/2016 6:41:26 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EntidadeDeFacturacao generated by hbm2java
 */
@Entity
@Table(name = "EntidadeDeFacturacao")
public class EntidadeDeFacturacao implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Collection<Processo> processos = new ArrayList<Processo>(0);

	public EntidadeDeFacturacao() {
	}

	public EntidadeDeFacturacao(String nome, Collection<Processo> processos) {
		this.nome = nome;
		this.processos = processos;
	}

	@Id
	@GeneratedValue

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entidadeDeFacturacao")
	public Collection<Processo> getProcessos() {
		return this.processos;
	}

	public void setProcessos(Collection<Processo> processos) {
		this.processos = processos;
	}

}
