package pt.gois.dtServices.entity;
// Generated 1/jun/2016 6:41:26 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Imovel generated by hbm2java
 */
@Entity
@Table(name = "Imovel")
public class Imovel implements java.io.Serializable {

	private Integer id;
	private String codigoPostal;
	private String crp;
	private String endereco;
	private String inquilino;
	private Collection<Processo> processos = new ArrayList<Processo>(0);

	public Imovel() {
	}

	public Imovel(String codigoPostal, String crp, String endereco, String inquilino, Collection<Processo> processos) {
		this.codigoPostal = codigoPostal;
		this.crp = crp;
		this.endereco = endereco;
		this.inquilino = inquilino;
		this.processos = processos;
	}

	@Id
	@GeneratedValue

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "codigoPostal")
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "crp")
	public String getCrp() {
		return this.crp;
	}

	public void setCrp(String crp) {
		this.crp = crp;
	}

	@Column(name = "endereco")
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "inquilino")
	public String getInquilino() {
		return this.inquilino;
	}

	public void setInquilino(String inquilino) {
		this.inquilino = inquilino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imovel")
	public Collection<Processo> getProcessos() {
		return this.processos;
	}

	public void setProcessos(Collection<Processo> processos) {
		this.processos = processos;
	}

}
