package pt.gois.dtServices.entity;
// Generated 1/jun/2016 6:41:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name = "Servico")
public class Servico implements java.io.Serializable {

	private Integer id;
	private Date dtCadastro;
	private Date dtFim;
	private Date dtInicio;
	private int estado;
	private Processo processo;
	private TipoServicoSolicitante tiposervicoSolicitante;

	public Servico() {
	}

	public Servico(int estado) {
		this.estado = estado;
	}

	public Servico(Date dtCadastro, Date dtFim, Date dtInicio, int estado, Processo processo,
			TipoServicoSolicitante tiposervicoSolicitante) {
		this.dtCadastro = dtCadastro;
		this.dtFim = dtFim;
		this.dtInicio = dtInicio;
		this.estado = estado;
		this.processo = processo;
		this.tiposervicoSolicitante = tiposervicoSolicitante;
	}

	@Id
	@GeneratedValue

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtCadastro")
	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtFim")
	public Date getDtFim() {
		return this.dtFim;
	}

	public void setDtFim(Date dtFim) {
		this.dtFim = dtFim;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtInicio")
	public Date getDtInicio() {
		return this.dtInicio;
	}

	public void setDtInicio(Date dtInicio) {
		this.dtInicio = dtInicio;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "processoId")
	public Processo getProcesso() {
		return this.processo;
	}

	public void setProcesso(Processo processo) {
		this.processo = processo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipoServico_SolicitanteId")
	public TipoServicoSolicitante getTiposervicoSolicitante() {
		return this.tiposervicoSolicitante;
	}

	public void setTiposervicoSolicitante(TipoServicoSolicitante tiposervicoSolicitante) {
		this.tiposervicoSolicitante = tiposervicoSolicitante;
	}

}
