package pt.gois.dtServices.entity;
// Generated 1/jun/2016 6:41:26 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoServico generated by hbm2java
 */
@Entity
@Table(name = "TipoServico")
public class TipoServico implements java.io.Serializable {

	private Integer id;
	private String descricao;
	private String nome;
	private Collection<TipoServicoSolicitante> tiposervicoSolicitantes = new ArrayList<TipoServicoSolicitante>(0);
	private double valor;

	public TipoServico() {
	}

	public TipoServico(double valor) {
		this.valor = valor;
	}

	public TipoServico(String descricao, String nome, Collection<TipoServicoSolicitante> tiposervicoSolicitantes,
			double valor) {
		this.descricao = descricao;
		this.nome = nome;
		this.tiposervicoSolicitantes = tiposervicoSolicitantes;
		this.valor = valor;
	}

	@Id
	@GeneratedValue

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposervico")
	public Collection<TipoServicoSolicitante> getTiposervicoSolicitantes() {
		return this.tiposervicoSolicitantes;
	}

	public void setTiposervicoSolicitantes(Collection<TipoServicoSolicitante> tiposervicoSolicitantes) {
		this.tiposervicoSolicitantes = tiposervicoSolicitantes;
	}

	@Column(name = "valor", nullable = false)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

}
