package pt.gois.dtServices.entity;
// Generated 1/jun/2016 6:41:26 by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoServicoSolicitante generated by hbm2java
 */
@Entity
@Table(name = "tiposervico_solicitante")
public class TipoServicoSolicitante implements java.io.Serializable {

	private Integer id;
	private Collection<Servico> servico = new ArrayList<Servico>(0);
	private Solicitante solicitante;
	private TipoServico tiposervico;
	private double valor;

	public TipoServicoSolicitante() {
	}

	public TipoServicoSolicitante(double valor) {
		this.valor = valor;
	}

	public TipoServicoSolicitante(Collection<Servico> servico, Solicitante solicitante, TipoServico tiposervico,
			double valor) {
		this.servico = servico;
		this.solicitante = solicitante;
		this.tiposervico = tiposervico;
		this.valor = valor;
	}

	@Id
	@GeneratedValue

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposervicoSolicitante")
	public Collection<Servico> getServico() {
		return this.servico;
	}

	public void setServico(Collection<Servico> servico) {
		this.servico = servico;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "solicitanteId")
	public Solicitante getSolicitante() {
		return this.solicitante;
	}

	public void setSolicitante(Solicitante solicitante) {
		this.solicitante = solicitante;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipoServicoId")
	public TipoServico getTiposervico() {
		return this.tiposervico;
	}

	public void setTiposervico(TipoServico tiposervico) {
		this.tiposervico = tiposervico;
	}

	@Column(name = "valor", nullable = false)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

}
