truncate table tiposervico;
truncate table processo;
truncate table entidadedefacturacao;
truncate table hibernate_sequence;
truncate table imovel;
truncate table orcamento;
truncate table servico;
truncate table solicitante;
truncate table tiposervico_solicitante;