package pt.gois.dtServices.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", schema = "dt_Services")
public class Log extends GeneralEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int id;
	private String level;
	private String codigo;
	private String table1;
	private Integer tableid;
	private String descricao;

	public Log() {
	}
	
	public Log( String level, String descricao){
		this.level = level;
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "level")
	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Column(name = "codigo")
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "table_1")
	public String getTable1() {
		return this.table1;
	}

	public void setTable1(String table1) {
		this.table1 = table1;
	}

	@Column(name = "tableid")
	public Integer getTableid() {
		return this.tableid;
	}

	public void setTableid(Integer tableid) {
		this.tableid = tableid;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
}
